### ISSUE TITLE
Enable Autodiscover clients in Prometheus formula in Uyuni 2020.03

### ISSUE THREAD

**Issue by bpetru** [uyuni-project/uyuni#2082]
Hi,
I try to configure monitoring with Prometheus, but after I activate **Autodiscover clients** in salt formula the Prometheus server dose not start.

The error is:
`--config.file=\"/etc/prometheus/prometheus.yml\"): parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 36: field uyuni_sd_configs not found in type config.plain" (--config.file=\"/etc/prometheus/prometheus.yml\"): parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 36: field uyuni_sd_configs not found in type config.plain"`

If I disable Autodiscover the server works ok, and I have Uyuni performance data.

**Comment by paususe** [comment]
@cavalheiro @renner 
Could you please take a look?

**Comment by srbarrios** [comment]
Might it just be an indentation issue?

**Comment by srbarrios** [comment]
Here an example:
```
# Managed systems metrics:
- job_name: 'mgr-clients'
  uyuni_sd_configs:
   - host: "http://server.url"
     username: "admin"
     password: "admin"
```

**Comment by calancha** [comment]
Using the following configuration (that is, I keep the wrong indentation), it works:
```
# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# {productname} self-health metrics
scrape_configs:
- job_name: 'mgr-server'
  static_configs:
    - targets:
      - 'vm153088.qa.prv.suse.net:9100'  # Node exporter
      - 'vm153088.qa.prv.suse.net:9187'  # PostgreSQL exporter
      - 'vm153088.qa.prv.suse.net:5556'  # JMX exporter (Tomcat)
      - 'vm153088.qa.prv.suse.net:5557'  # JMX exporter (Taskomatic)
      - 'vm153088.qa.prv.suse.net:9800'  # Taskomatic
    - targets:
      - 'vm153088.qa.prv.suse.net:80'    # Message queue
      labels:
        __metrics_path__: /rhn/metrics

# Managed systems metrics:
- job_name: 'mgr-clients'
  uyuni_sd_configs:
   - host: "http://vm153088.qa.prv.suse.net"
     username: "admin"
     password: "admin"

```
Here, the SUMA server is the one for testing beta 2, and the monitoring client is a sles15sp2.
