### ISSUE TITLE
Uyuni Enhancement Request - Ansible Role variable customization in UI

### ISSUE THREAD

**Issue by stdevel** [uyuni-project/uyuni#4743]
# Short description

I love the way Salt Formula variables can be set using the Uyuni web UI. It would be awesome to have the same look & feel for Ansible Role variables.

# Details 

Maybe the same form definitions (*like for Salt Formulas*) can be used for Ansible?

- `/usr/share/susemanager/formulas/metadata/<name>`
- `/usr/share/susemanager/formulas/roles/<name>`

The `roles` folder could contain particular Ansible role folders. Metadata files could pin the UI elements to Ansible variables.

**Comment by stdevel** [comment]
Hello community,
are there any news on this?

I have several customers that would love to see this feature coming.

**Comment by vampywiz17** [comment]
+1 it sounds good!!

**Comment by admd** [comment]
Hi @stdevel, not exactly for roles that you have asked for here but  for now we’ll introduce a simple UI specifically for playbook variables—a simple interface allowing users to set variables defined within the playbook.

Example

```
- name: Example playbook with various variable types
  hosts: all
  vars:
    # List variable
    software_packages:
      - git
      - nginx
      - curl

    # Dictionary variable
    user_info:
      username: "devuser"
      uid: 1001
      home_dir: "/home/devuser"

    # Integer variable
    max_open_files: 1024

    # Boolean variable
    enable_firewall: true

    # String variable
    welcome_message: "Welcome to the server setup!"

  tasks:
    # Install multiple packages using the list variable
    - name: Install software packages
      apt:
        name: "{{ software_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    # Create a user using dictionary variable
    - name: Create a new user
      user:
        name: "{{ user_info.username }}"
        uid: "{{ user_info.uid }}"
        home: "{{ user_info.home_dir }}"
        state: present

    # Configure system with integer variable
    - name: Set max open files limit
      lineinfile:
        path: /etc/security/limits.conf
        line: "* soft nofile {{ max_open_files }}"
      become: true

    # Use boolean to conditionally enable a task
    - name: Enable firewall if requested
      service:
        name: ufw
        state: started
      when: enable_firewall

    # Display the welcome message using string variable
    - name: Print welcome message
      debug:
        msg: "{{ welcome_message }}"
```

So for now, the UI will allow users to set values for anything defined under vars in the playbook. The default values will be those specified in the playbook but can be edited to fit specific needs. 
```
  vars:
    # List variable
    software_packages:
      - git
      - nginx
      - curl

    # Dictionary variable
    user_info:
      username: "devuser"
      uid: 1001
      home_dir: "/home/devuser"

    # Integer variable
    max_open_files: 1024

    # Boolean variable
    enable_firewall: true

    # String variable
    welcome_message: "Welcome to the server setup!"
```

It may not offer a high level of flexibility, but it’s a solid starting point for us.
