### ISSUE TITLE
New Ubuntu Errata Function tries to install packages from wrong OS version

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#5023]
# Problem description

Our Uyuni system currently has base-channels and CV-channels for Ubuntu 20.04, 18.04 and 16.04.
The download/parsing of the Errata/Patch data worked flawlessly, which already helps a lot!

But since we are using the patching function of Uyuni in a automatic manner we are triggering all relevant patches for every host via the API. After the first run I noticed then that something must be wrong (this is from the salt state):

```yaml
pkg_|-pkg_installed_|-pkg_installed_|-installed:
    name: pkg_installed
    result: false
    changes: {
        }
    comment: |-
        Problem encountered installing package(s). Additional info follows:

        errors:
            - Running scope as unit: run-r86dd5a7af19245afb37cbf1a472410f8.scope
              E: Version '2.2.9-1ubuntu0.2' for 'libexpat1' was not found
              E: Version '2.31-0ubuntu9.7' for 'libc6' was not found
    __sls__: packages.pkginstall
    __run_num__: 4.0
    start_time: '01:50:23.691071'
    duration: 2461.931
    __id__: pkg_installed
```

This is from this 18.04 machine:

```bash
spacecmd {SSM:0}> system_listerrata 1000010088
Security Errata
---------------
5310-1          Several security issues were fixed in GNU C        stable     2022-03-01
5298-1          Several security issues were fixed in the Linux    stable     2022-02-22
5288-1          Several security issues were fixed in Expat.       stable     2022-02-21
```

As far as I could see in these Erratas there are both 18.04 and 20.04 channels linked:
![image](https://user-images.githubusercontent.com/42647570/158761823-e1d3b2fe-2a06-4992-9674-caaa76342f68.png)

(btw I don't see the new Ubuntu Errata in `spacecmd` with the `errata_*` commands, so I couldn't output the data from the picture with `errata_details`)

## Version of Uyuni Server and Proxy (if used)

```bash
# zypper info Uyuni-Server-release
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.02-171.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.02-171.1.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

@lucidd I hope it is okay that I directly tag you here, as I didn't see you in Gitter
