### ISSUE TITLE
[Feature Request] Add filtered Module Stream metadata to CLs

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#5604]
As discussed in the today's Community Hours I would like to propose a improvement to the Module Stream implementation (for Enterprise Linux 8, 9, Fedora 29, 30, 31, 32, 33, 34, 35, 36).

Right now the situation is, you can sync the repos to Uyuni, but if you want to use the Module Streams you can only add them in synced (Base) repos.
To make Uyuni deal with the update process, it is needed to create Content Lifecycle Environments.
The issue there is, that as soon as a machine is in the CL environment, it doesn't see any Module Stream data anymore, as these just get stripped out there, this creates at least three major problems:
- You are not able to add any Streams to the machine, it will be able to access the packages, but it won't be able to add the Stream (there are at least a handful of installers which will expect to be able to check/enable the Streams)
- There are several Streams which don't have the default enabled flag set, which means the packages of these are normally not accessible before manually enabling the Stream (so creates unknown behavior)
- There is also package group information in the Streams metadata

I know that making Uyuni Module Streams agnostic looks like a lot of work, and I also think that it would be,
but as discussed, there might be a rather resource saving way to implement something so dnf doesn't get completely confused.

I'm not really a programmer, but for me it sounds like the CL creator (only for the initial build process) would need a function to be able to take the ingest modules.yaml file and Filter data which gets added to the CL, and just filters the Streams in this file which are present as a Filter.

So to visualize it a bit the original modules.yaml has 2 document types in it, `modulemd-defaults` and `modulemd`, these always look like this:

```
---
document: modulemd-defaults
version: 1
data:
  module: container-tools
  stream: "rhel8"
  profiles:
    1.0: [common]
    2.0: [common]
    3.0: [common]
    4.0: [common]
    rhel8: [common]
...
---
document: modulemd
version: 2
data:
  name: container-tools
  stream: "1.0"
  version: 8050020211109140251
  context: faa19cc5
  arch: x86_64
  summary: Stable versions of podman 1.0, buildah 1.5, skopeo 0.1, runc, conmon, CRIU, ...
  description: >-
    Stable versions of podman 1.0 , buildah 1.5, skopeo 0.1, runc, conmon, CRIU, Udica, ...
  license:
    module:
    - MIT
    content:
    - ASL 2.0
    - GPLv2
    - GPLv3+
  xmd: {}
  dependencies:
  - buildrequires:
      go-toolset: [rhel8]
      golang-ecosystem: [1.0]
      platform: [el8.5.0]
    requires:
      platform: [el8]
  references:
    community: https://github.com/projectatomic
    documentation: https://projectatomic.io
    tracker: https://github.com/projectatomic
  profiles:
    common:
      rpms:
      - buildah
      - container-selinux
      - ***
  api:
    rpms:
    - buildah
    - container-selinux
    - ***
  buildopts:
    rpms:
      macros: >
        %_with_ignore_tests 1
  components:
    rpms:
      buildah:
        rationale: Primary component of this module
        ref: 7d7e010bae87dd13000b3c9c633527beba1f1066
        arches: [aarch64, i686, x86_64]
    ***
      ***
        ***
        ***
  artifacts:
    rpms:
    - buildah-0:1.5-8.gite94b4f9.module+el8.5.0+681+c9a1951f.src
    - buildah-0:1.5-8.gite94b4f9.module+el8.5.0+681+c9a1951f.x86_64
    - ***
...
```

There is only at most 1 `modulemd-defaults` item and at least 1 `modulemd` item for every Module Stream. (if there is no default Stream set, there is no `modulemd-defaults` available)
All of them start with `---` and end with `...`

So filtering for the set modules would mean removing the not present profiles from the dictionary in the `modulemd-defaults` item (if present),
and completely removing the `modulemd` items, which are filtered out.

And the file which will get emmited from this would need to be put in the CL repo structure and referenced in the repomd.xml file as data type `modules` (I guess the metadata for the other stuff in the repomd.xml file is already autogenerated anyways as this changes as well)

I hope this is understandable enough and makes sense to implement it in this way,
if not I'm also fine with a better solution! 🙂

If any further knowledge is needed from my side I would really like to help!
Thank you very much!
