### ISSUE TITLE
locale-formula failing on "Apply highstate" on mgr_locale_package

### ISSUE THREAD

**Issue by vandabarata** [uyuni-project/uyuni#7597]
### Problem description

When applying the `locale-formula` on Uyuni, based on an openSUSE Leap image, it fails on the `mgr_locale_package` stage because it attemps to install `glibc-locale` which doesn't seem to be available on Leap - I could only find `glibc-locale-base`. When investigating, it seems the problem comes from [this part of the code in the formula](https://github.com/SUSE/salt-formulas/blob/master/locale-formula/states/map.jinja).  

### Steps to reproduce

1. On an Uyuni server based on Leap, install the `locale-formula` and enable it
2. Apply highstate - this will fail with the following result:
```yaml
----------
          ID: mgr_locale_package
    Function: pkg.installed
        Name: glibc-locale
      Result: false
     Comment: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-rc4745e0e300844f081d2cf771d115625.scope
Package 'glibc-locale' not found.Loading repository data...
Reading installed packages...
     Started: 23:35:11.939055
    Duration: 141.892
         SLS: locale
     Changed: {}
```

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : server_devel_repo
Name           : Uyuni-Server-release
Version        : 2023.09-230900.207.6.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.09-230900.207.6.uyuni3.src
Summary        : Uyuni Server
```
