### ISSUE TITLE
Misbehavior with multiple beacons same kind (inotify)

### ISSUE THREAD

**Issue by kordhaldrum** [uyuni-project/uyuni#8133]
### Problem description

 I am trying to create multiple inotify beacons, each one would trigger a event and trigger different reactor.

But Salt Minion is not recognizing and is acting weird when we have multiple beacons inotify using beacon_module: inotify setting, first one work fine but second one give error ignoring its tags like trying to trigger itself over first beacon name.

Uyuni Version: 2023-10
Operating System on minion: Oracle Linux 9
python3-inotify-0.9.6-25
Venv-Salt-Minion: venv-salt-minion-3006.0-22.1

### Steps to reproduce

1 - Deploy the follow beacons to your minion:
 ```
beacons:
  inotify_file01:
  - enable: true
  - files:
      /etc/file01:
        mask:
        - modify
  - beacon_module: inotify
  - disable_during_state_run: true
  inotify_file02:
  - enable: true
  - files:
      /etc/file02:
        mask:
        - modify
  - beacon_module: inotify
  - disable_during_state_run: true
```
2 - Expected behavior
A different event tag for each when file01 or file02 modified, like this;
```
salt/beacon/minion_id/inotify_file01//etc/file01 {
    "_stamp": "2024-01-10T15:59:42.867553",
    "change": "IN_IGNORED",
    "id": "minion_id",
    "path": "/etc/file01"
}
salt/beacon/minion_id/inotify_file02//etc/file02 {
    "_stamp": "2024-01-10T15:59:42.867553",
    "change": "IN_IGNORED",
    "id": "minion",
    "path": "/etc/file02"
}
```
But instead, file01 beacon work fine, but file02 trigger this event on master:
```
salt/beacon/minion_id/inotify_file01/	{
    "_stamp": "2024-01-10T16:05:50.213151"
}
```
And this on minion side:
```
[ERROR   ] Unable to start inotify_file01 beacon, '/'
```

### Uyuni version

```bash
Uyuni Version: 2023-10
Venv-Salt-Minion: venv-salt-minion-3006.0-22.1
Operating System on minion: Oracle Linux 9
```
