### ISSUE TITLE
Include 

### ISSUE THREAD

**Issue by ypid-geberit** [uyuni-project/uyuni#889]
https://github.com/uyuni-project/uyuni/blob/238ac9f0911cbe60d7d24f25ee0afc14a8ee45de/java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java#L150

**Comment by joesusecom** [comment]
@ypid-geberit: At this point the group_ids and there exposure to pillars are an implementation detail. Assigning Salt states to groups is supposed to happen through the UI or API. So at least for states there shouldn‘t really be a use case for needing the group “pretty names” directly in Salt.

But I agree that it would be nice if group pillars were available for targeting from the Salt CLI. There’s one caveat: Group names are only unique within one organization. So we’d need to generate pillars like “org1_mygroup” to make them globally unique.

We’re looking into this as part of 4.1 development.

**Comment by Shirocco88** [comment]
@joesusecom : 
is this feature already available in uyuni-2021.06 ?

**Comment by aaannz** [comment]
No, this is not done (yet).
As a workaround you can use postgres salt pillar:

Add following to the `/etc/salt/master.d/susemanager.conf` on uyuni server:
```yaml
postgres:
  db: susemanager
  host: localhost
  pass: spacewalk
  port: 5432
  user: spacewalk

ext_pillar:
  - postgres:
      'susemanager':
         query: "SELECT 'groups', CONCAT(SG.org_id,'-',SG.name) FROM rhnServerGroup AS SG,
                        rhnServerGroupMembers AS SGM,
                        rhnServer AS S
                 WHERE SGM.server_group_id = SG.id AND
                       SGM.server_id=S.id AND
                       SG.group_type IS NULL AND
                       S.name LIKE %s"
         as_list: True
         depth: 2
         with_list: [1]
```
(courtesy of @vzhestkov)

This will add `org_id-group_name` to the `groups` pillar. e.g. '1-test' for org id 1 and group name test.
