### ISSUE TITLE
.github/ISSUE_TEMPLATE/bugreport.yaml error

### ISSUE THREAD

**Issue by kcote-ncar** [uyuni-project/uyuni#9815]
Hello,

The [github issue template](https://github.com/uyuni-project/uyuni/blob/master/.github/ISSUE_TEMPLATE/bugreport.yaml) has a syntax error:
"YAML syntax error: (): mapping values are not allowed in this context at line 43 column 16."

It appears line 43 is missing the validations section:
```yaml
  - type: textarea
     attributes:
       label: uyuni-tools version used to deploy/manage the server or proxy (if relevant)
       placeholder: |
         Paste output of `zypper info mgradm`, or `zypper info mgrpxy`, or `zypper info mgrctl`, depending on the context
       render: bash
```
Should it be configured as?:
```yaml
  - type: textarea
     attributes:
       label: uyuni-tools version used to deploy/manage the server or proxy (if relevant)
       placeholder: |
         Paste output of `zypper info mgradm`, or `zypper info mgrpxy`, or `zypper info mgrctl`, depending on the context
       render: bash
    validations:
      required: false
```
Thanks!
